### PR TITLE
Use future parser

### PR DESCRIPTION
**Pull request by jschlyter**
Enable future parser for puppet_manifest_syntax_check.sh

### CODE REVIEW

**Comment by drwahl** [comment]
Thanks for cleaning up that bug.

**Comment by walkamongus** [comment]
this broke all parser validations for me under Puppet 4.2.2 with ```Error: Could not parse application options: invalid option: --parser```

**Comment by jschlyter** [comment]
So puppet 4.x does not recognize the parser option at all?

**Comment by walkamongus** [comment]
it seems like that is the case -- I tried moving the option around, passing it after both ```parser``` and ```validate``` as well as passing it right after ```puppet``` and it threw the same error each time.

I can't find documentation of it being removed (yet), however.

**Comment by jschlyter** [comment]
I've updated the code to enable the future parser only for Puppet 3.7.x and 3.8.x, please check out https://github.com/jschlyter/puppet-git-hooks/commit/36fdf23b627ad95d37e050a79cfb3eacf6f1bad5.

**Comment by walkamongus** [comment]
I think this will work but FWIW, I think I lean towards making the future parser a config option as in #45.

**Comment by jschlyter** [comment]
Yes, that is probably a better idea

**Comment by jhg03a** [comment]
Thanks!

**Pull request merged**
